# Generated by Django 3.2.15 on 2022-08-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='img/article_default.jpg', upload_to='article_cover'),
        ),
    ]
